import * as THREE from 'https://esm.sh/three@0.180.0';
import {GLTFLoader} from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js?deps=three@0.180.0';
const $=id=>document.getElementById(id),menu=$('menu'),creator=$('creator'),game=$('game'),view=$('viewport'),hud=$('hud');
const K='minisims-deluxe-save';let S={name:'Владимир',gender:'male',skin:'#d59b72',hair:'#39271f',money:1850,time:480,day:1,hunger:82,energy:76,hygiene:82,fun:70,social:64,cooking:1,mood:75,x:0,z:4};try{Object.assign(S,JSON.parse(localStorage.getItem(K)||'{}'))}catch(e){}
let scene,camera,renderer,hero,mixer,acts={},ray,clock=new THREE.Clock(),target=null,joy={x:0,y:0},keys={},solids=[],items=[],busy=false,mini=null,paused=false,lastHud=0;
const show=e=>{[menu,creator,game].forEach(x=>x.classList.add('hidden'));e.classList.remove('hidden')};const save=()=>localStorage.setItem(K,JSON.stringify(S));
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function M(c,r=.8){return new THREE.MeshStandardMaterial({color:c,roughness:r})}function box(n,x,y,z,w,h,d,c,solid=true){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),M(c));m.name=n;m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);if(solid)solids.push({x,z,w,d});return m}
function makeWorld(){
 box('floor',0,-.08,3,18,.16,18,0xd5c4aa,false);box('back',0,2,-6,18,4,.25,0xe9e1d6);box('left',-9,2,3,.25,4,18,0xe9e1d6);box('right',9,2,3,.25,4,18,0xe9e1d6);
 box('partition',0,2,-2.5,.22,4,7,0xd8cec0);box('kitchen',4.7,.65,-4.4,5.5,1.3,1.3,0x66798b);box('fridge',7,1.3,-3,1.1,2.6,1.1,0xf0f1ef);box('bed',-5,.65,-4.2,3.3,1.15,3.8,0x596f9a);box('blanket',-5,1.28,-4,2.9,.12,2.8,0x829fc8,false);box('sofa',-5,.65,3.8,4.1,1.2,1.5,0x806a60);box('tv',0,1.55,5.3,2.8,1.6,.2,0x14191d);box('tvstand',0,.55,5.4,3,.8,.8,0x674b38);box('desk',4.5,.65,2.4,2.8,1.2,1.2,0x75533a);box('monitor',4.5,1.45,2.1,1.8,1.2,.12,0x18262e);box('shower',6.7,1.1,-.6,1.8,2.2,1.8,0x9cc4ca);box('toilet',4.5,.6,5,1,1.1,1.3,0xf3efe8);
 items=[['Кухня','🍳',4.7,-3.3,'cook','Готовить'],['Кровать','🛏️',-5,-3.4,'sleep','Спать'],['Телевизор','📺',0,4.1,'tv','Смотреть ТВ'],['Душ','🚿',6.7,-.6,'shower','Принять душ'],['Компьютер','💻',4.5,2.9,'work','Работать'],['Диван','💬',-5,3.0,'social','Общаться']].map(a=>({name:a[0],icon:a[1],x:a[2],z:a[3],type:a[4],label:a[5]}));
 for(let i=0;i<26;i++){let x=-27+Math.random()*54,z=-2+Math.random()*50;if(Math.abs(x)<11&&z<11)continue;box('trunk',x,.8,z,.38,1.6,.38,0x65482f);let c=new THREE.Mesh(new THREE.SphereGeometry(1.5,12,8),M(0x46764b));c.position.set(x,2.5,z);c.castShadow=true;scene.add(c)}
}
function makeHero(){hero=new THREE.Group();hero.position.set(S.x,0,S.z);scene.add(hero);const loader=new GLTFLoader();loader.load('https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb',g=>{let model=g.scene;model.scale.setScalar(0.95);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});hero.add(model);mixer=new THREE.AnimationMixer(model);for(const a of g.animations)acts[a.name]=mixer.clipAction(a);playAnim('Idle')},undefined,()=>{fallbackHero()})}
function fallbackHero(){const b=new THREE.Mesh(new THREE.CapsuleGeometry(.45,.9,8,14),M(0x477bb8));b.position.y=1.1;hero.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.44,20,14),M(S.skin));h.position.y=2.1;hero.add(h)}
function playAnim(name){if(!mixer)return;const map={Idle:'Idle',Walk:'Walking',Run:'Running',Sit:'Sitting',Stand:'Standing',Talk:'Yes',Wave:'Wave',Work:'Standing',Cook:'Punch'};let a=acts[map[name]||name]||acts.Idle;if(!a)return;Object.values(acts).forEach(x=>{if(x!==a)x.fadeOut(.12)});a.reset().fadeIn(.12).play()}
function init(){if(renderer)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc7da);scene.fog=new THREE.Fog(0x9fc7da,28,75);camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.1,150);camera.position.set(12,10,16);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;view.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xeaf7ff,0x4f6749,2.2));let sun=new THREE.DirectionalLight(0xffefd0,3.5);sun.position.set(-14,23,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);makeWorld();makeHero();makeJoystick();ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',tap);addEventListener('resize',resize);requestAnimationFrame(loop)}
function makeJoystick(){let j=document.createElement('div');j.id='joystick';j.innerHTML='<div class="joy-ring"><div class="joy-knob"></div></div>';game.appendChild(j);let r=j.firstElementChild,k=r.firstElementChild,on=false;function set(e){let b=r.getBoundingClientRect(),x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,l=Math.hypot(x,y),m=40;if(l>m){x=x/l*m;y=y/l*m}joy.x=x/m;joy.y=y/m;k.style.transform=`translate(${x}px,${y}px)`}r.onpointerdown=e=>{e.stopPropagation();on=true;r.setPointerCapture(e.pointerId);set(e)};r.onpointermove=e=>{if(on){e.stopPropagation();set(e)}};r.onpointerup=r.onpointercancel=e=>{on=false;joy.x=joy.y=0;k.style.transform=''}}
function tap(e){if(mini||e.target!==renderer.domElement)return;let b=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);let p=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p))target={x:THREE.MathUtils.clamp(p.x,-8,8),z:THREE.MathUtils.clamp(p.z,-5,13)}}
function blocked(x,z){let r=.4;return solids.some(o=>x>o.x-o.w/2-r&&x<o.x+o.w/2+r&&z>o.z-o.d/2-r&&z<o.z+o.d/2+r)||x<-8.2||x>8.2||z<-5.5||z>13}
function move(dx,dz){let nx=hero.position.x+dx,nz=hero.position.z+dz;if(!blocked(nx,hero.position.z))hero.position.x=nx;if(!blocked(hero.position.x,nz))hero.position.z=nz}
function hudRender(){if(!hero)return;let near=items.map(o=>({...o,d:Math.hypot(o.x-hero.position.x,o.z-hero.position.z)})).filter(o=>o.d<3.3).sort((a,b)=>a.d-b.d);hud.innerHTML=`<div class="sim-top"><div class="profile"><div class="portrait">${S.gender==='male'?'♂':'♀'}</div><div><strong>${S.name}</strong><small>День ${S.day} · ${Math.floor(S.time/60)}:${String(Math.floor(S.time%60)).padStart(2,'0')} · ${S.action||'Свободен'}</small></div></div><div class="needs-card"><div class="needs-title">ПОТРЕБНОСТИ</div>${[['🍽️','Голод','hunger'],['⚡','Энергия','energy'],['🚿','Гигиена','hygiene'],['🎮','Досуг','fun'],['💬','Общение','social']].map(a=>`<div class="need"><span>${a[0]} ${a[1]}</span><b>${Math.round(S[a[2]])}</b><i><em style="width:${Math.max(0,S[a[2]])}%"></em></i></div>`).join('')}</div><div class="top-actions"><button id="pause">Ⅱ</button><button id="save">💾</button></div></div><div class="bottom-hud"><div class="sim-stats"><strong>§ ${Math.round(S.money)}</strong><span>Настроение ${Math.round(S.mood||70)}</span><span>Кулинария ${S.cooking.toFixed(1)}</span></div><div class="context-actions">${near.map(o=>`<button class="context" data-o="${o.name}"><b>${o.icon}</b><span>${o.name}</span><small>${o.label}</small></button>`).join('')}</div></div>`;$('save').onclick=e=>{e.stopPropagation();save();toast('Сохранено')};$('pause').onclick=e=>{e.stopPropagation();paused=!paused};hud.querySelectorAll('[data-o]').forEach(b=>b.onclick=e=>{e.stopPropagation();act(b.dataset.o)})}
function act(name){if(busy)return;let o=items.find(x=>x.name===name);if(!o)return;if(Math.hypot(o.x-hero.position.x,o.z-hero.position.z)>1.7){target={x:o.x,z:o.z+(o.z>0?-1.25:1.25)};S.action='Идёт к '+name;return}if(o.type==='sleep'){busy=true;S.action='Спит';playAnim('Sit');setTimeout(()=>{S.energy=Math.min(100,S.energy+45);S.action='Проснулся';busy=false},5000);return}if(o.type==='shower'){busy=true;S.action='Принимает душ';playAnim('Wave');setTimeout(()=>{S.hygiene=Math.min(100,S.hygiene+40);S.action='Свободен';busy=false},3200);return}if(o.type==='tv'){busy=true;S.action='Смотрит ТВ';playAnim('Sit');setTimeout(()=>{S.fun=Math.min(100,S.fun+30);S.action='Свободен';busy=false},2800);return}if(o.type==='social'){busy=true;S.action='Общается';playAnim('Talk');setTimeout(()=>{S.social=Math.min(100,S.social+32);S.action='Свободен';busy=false},2600);return}playAnim(o.type==='cook'?'Cook':'Work');startMini(o.type,o.name)}
function startMini(type,name){if(mini)return;mini={type,name,p:.08,d:1,round:1,score:0};let e=document.createElement('div');e.id='mini';e.className='mini-overlay';e.innerHTML=`<div class="mini-card"><div class="mini-round">${type==='cook'?'КУХНЯ':'РАБОТА'} · РАУНД 1/3</div><h2>${type==='cook'?'Приготовление блюда':'Рабочая задача'}</h2><p>${type==='cook'?'Три этапа: нарезка → жарка → подача. Чем точнее тайминг, тем выше качество.':'Три задания на реакцию. Ошибки снижают заработок.'}</p><div class="skill-track"><div class="skill-zone"></div><div class="skill-cursor" id="cursor"></div></div><button id="hit">ПОПАСТЬ В ЗОНУ</button><div class="mini-round" id="round">Точность: 0</div></div>`;game.appendChild(e);e.querySelector('#hit').onclick=x=>{x.stopPropagation();hitMini()}}
function hitMini(){let d=Math.abs(mini.p-.5),score=d<.10?3:d<.22?2:0;mini.score+=score;if(mini.round<3){mini.round++;mini.d+=.45;mini.p=.18+.64*Math.random();$('#mini .mini-round:last-child').textContent=`Точность: ${mini.score} · Раунд ${mini.round}/3`;return}let result=mini.score>=8?'ОТЛИЧНО':mini.score>=5?'ХОРОШО':'ПЛОХО';if(mini.type==='cook'){S.hunger=Math.min(100,S.hunger+(result==='ОТЛИЧНО'?36:result==='ХОРОШО'?23:8));S.cooking+=result==='ОТЛИЧНО'?.4:result==='ХОРОШО'?.2:.05}if(mini.type==='work')S.money+=result==='ОТЛИЧНО'?130:result==='ХОРОШО'?75:20;$('#mini').remove();mini=null;S.action=result;save();toast(`${mini?.type||'Действие'}: ${result}`)}
function tick(dt){if(paused||!hero)return;S.time+=dt*.75;if(S.time>=1440){S.time=0;S.day++}S.hunger-=dt*.018;S.energy-=dt*.009;S.hygiene-=dt*.012;S.fun-=dt*.01;S.social-=dt*.007;S.mood=(S.hunger+S.energy+S.hygiene+S.fun+S.social)/5;if(mini){mini.p+=mini.d*dt;if(mini.p>.98||mini.p<.02)mini.d*=-1;let c=$('cursor');if(c)c.style.left=`calc(${mini.p*100}% - 3px)`;return}let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0)+joy.x,dz=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0)+joy.y;if(target&&!busy){dx+=target.x-hero.position.x;dz+=target.z-hero.position.z;let l=Math.hypot(dx,dz);if(Math.hypot(target.x-hero.position.x,target.z-hero.position.z)<.3){target=null;let o=items.find(x=>Math.hypot(x.x-hero.position.x,x.z-hero.position.z)<1.9);if(o)act(o.name)}else{dx/=l;dz/=l}}if((dx||dz)&&!busy){let l=Math.hypot(dx,dz);move(dx/l*dt*3.1,dz/l*dt*3.1);hero.rotation.y=Math.atan2(dx,dz);playAnim('Walk')}else if(!busy)playAnim('Idle');if(busy&&!mini&&hero){const t=performance.now()*.004;if(hero.children[0]){hero.children[0].rotation.z=Math.sin(t)*.035;hero.children[0].position.y=0.02+Math.abs(Math.sin(t))*0.015}}else if(hero&&hero.children[0]){hero.children[0].rotation.z=0;hero.children[0].position.y=0}if(mixer)mixer.update(dt)}
function loop(){let dt=Math.min(clock.getDelta(),.05);tick(dt);if(hero){camera.position.lerp(new THREE.Vector3(hero.position.x+10,9.5,hero.position.z+12),.06);camera.lookAt(hero.position.x,1.1,hero.position.z)}if(performance.now()-lastHud>350){hudRender();lastHud=performance.now()}renderer.render(scene,camera);requestAnimationFrame(loop)}
function resize(){if(renderer){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
$('playBtn').onclick=()=>{show(game);init()};$('continueBtn').onclick=()=>{show(game);init()};$('newBtn').onclick=()=>show(creator);$('backBtn').onclick=()=>show(menu);$('startBtn').onclick=()=>{S.name=$('nameInput').value.trim()||'Сим';save();show(game);init()};
document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{S.gender=b.dataset.gender;document.querySelectorAll('[data-gender]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{S.skin=b.dataset.skin;document.querySelectorAll('[data-skin]').forEach(x=>x.classList.toggle('active',x===b));$('pHead').style.background=S.skin});document.querySelectorAll('[data-hair]').forEach(b=>b.onclick=()=>{S.hair=b.dataset.hair;document.querySelectorAll('[data-hair]').forEach(x=>x.classList.toggle('active',x===b));$('pHair').style.background=S.hair});