import * as THREE from 'https://esm.sh/three@0.180.0';
const $=id=>document.getElementById(id),menu=$('menu'),creator=$('creator'),game=$('game'),view=$('viewport'),hud=$('hud');
const SAVE='minisims-v60';let S={name:'Владимир',gender:'male',skin:'#d59b72',hair:'#39271f',money:1850,time:510,day:1,hunger:82,energy:76,hygiene:82,fun:70,social:64,cooking:1,logic:1,mood:75,x:0,z:4};try{Object.assign(S,JSON.parse(localStorage.getItem(SAVE)||'{}'))}catch{}
let scene,camera,renderer,hero,parts={},ray,target=null,joy={x:0,y:0},keys={},solids=[],items=[],busy=false,mini=null,paused=false,last=performance.now(),camGoal=new THREE.Vector3();
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:0});
function show(e){[menu,creator,game].forEach(x=>x.classList.add('hidden'));e.classList.remove('hidden')};function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)};function save(){localStorage.setItem(SAVE,JSON.stringify(S));toast('Сохранено')}
function mesh(g,c){let m=new THREE.Mesh(g,M(c));m.castShadow=m.receiveShadow=true;return m}function box(n,x,y,z,w,h,d,c,solid=true){let m=mesh(new THREE.BoxGeometry(w,h,d),c);m.name=n;m.position.set(x,y,z);scene.add(m);if(solid)solids.push({x,z,w,d});return m}
function roundBox(n,x,y,z,w,h,d,c,r=.18){let m=mesh(new THREE.BoxGeometry(w,h,d),c);m.position.set(x,y,z);m.name=n;scene.add(m);return m}
function cyl(x,y,z,r,h,c){let m=mesh(new THREE.CylinderGeometry(r,r*.9,h,18),c);m.position.set(x,y,z);scene.add(m);return m}
function tree(x,z){cyl(x,.8,z,.18,1.6,0x62462f);let a=mesh(new THREE.SphereGeometry(1.15,12,10),0x4f8a55);a.position.set(x,2.1,z);scene.add(a);let b=mesh(new THREE.SphereGeometry(.78,12,10),0x61965d);b.position.set(x+.5,2.35,z-.15);scene.add(b)}
function makeWorld(){
 let ground=mesh(new THREE.PlaneGeometry(100,100),0x6f9967);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 // street and sidewalks
 box('street',0,.01,18,90,.03,9,0x5f666b,false);box('sidewalk',0,.04,12,90,.06,2.2,0xc7c1b4,false);for(let x=-40;x<40;x+=6)box('mark',x,.045,18,3,.02,.12,0xd8d0bd,false);
 // house, open front, separated rooms
 box('back',0,2,-7,22,4,.3,0xe8ded0);box('L',-11,2,2,.3,4,18,0xe8ded0);box('R',11,2,2,.3,4,18,0xe8ded0);box('front1',-7.8,2,11,6.4,4,.3,0xe8ded0);box('front2',7.8,2,11,6.4,4,.3,0xe8ded0);box('floor',0,.02,2,22,.1,18,0xbca889,false);
 // interior details
 box('kitchen',5,.6,-4,7,1.2,1.1,0x536b7c);box('counter',5,.62,-2.65,7,.1,1.1,0x8a674c,false);box('fridge',8.5,1.35,-4.6,1.1,2.7,1.1,0xe9ecec);box('stove',3,.67,-2.65,1.4,.12,.9,0x24282b,false);
 box('bed',-5,.65,-3.8,4,1.1,4,0x526e9e);box('pillow',-5,1.25,-5.1,3.1,.18,.8,0xf2ede4,false);box('sofa',-5,.7,4.2,4.5,1.3,1.5,0x80675f);box('tvstand',0,.55,5.6,3.8,.9,.9,0x654832);box('tv',0,1.75,5.15,3.2,1.8,.15,0x151a1e);box('desk',5,.65,4.3,3.2,1.2,1.3,0x76533b);box('screen',5,1.6,3.85,1.8,1.3,.12,0x172831);box('shower',8.3,1.1,-.5,2,2.2,2,0x9fcbd0);box('toilet',5.8,.6,-.4,1,1.1,1.3,0xf1ede4);
 for(let x=-10;x<=10;x+=2.5){box('fence',x,1,12.4,.13,2,.13,0x896947)}for(let x=-30;x<=30;x+=10){cyl(x,1.7,13,.1,3.4,0x33383b);let l=new THREE.PointLight(0xffdfae,1.2,7);l.position.set(x,3.2,13);scene.add(l)}
 for(let i=0;i<36;i++){let x=-40+Math.random()*80,z=-28+Math.random()*58;if(Math.abs(x)<14&&z<14)continue;tree(x,z)}
 items=[['Холодильник','🍳',8.5,-3.3,'cook','Готовить'],['Кровать','🛏️',-5,-1.9,'sleep','Спать'],['Телевизор','📺',0,4.1,'tv','Смотреть'],['Душ','🚿',8.3,1.0,'shower','Душ'],['Компьютер','💻',5,3.0,'work','Работать'],['Диван','💬',-5,3.0,'social','Общаться']].map(a=>({name:a[0],icon:a[1],x:a[2],z:a[3],type:a[4],label:a[5]}));
}
function human(){hero=new THREE.Group();hero.position.set(S.x,0,S.z);scene.add(hero);let skin=M(S.skin),hair=M(S.hair),shirt=M(S.gender==='female'?0xa94f71:0x3e79b7),pants=M(0x26374d),shoe=M(0x202326);
 let pelvis=mesh(new THREE.BoxGeometry(.55,.42,.34),pants);pelvis.position.y=.95;hero.add(pelvis);parts.pelvis=pelvis;
 let torso=mesh(new THREE.CapsuleGeometry(.43,.7,8,16),shirt);torso.position.y=1.48;hero.add(torso);parts.torso=torso;
 let head=mesh(new THREE.SphereGeometry(.34,24,18),skin);head.scale.y=1.08;head.position.y=2.43;hero.add(head);parts.head=head;
 let h=mesh(new THREE.SphereGeometry(.36,24,12,0,Math.PI*2,0,Math.PI*.58),hair);h.position.set(0,2.58,0);hero.add(h);parts.hair=h;
 for(let side of[-1,1]){let leg=new THREE.Group();leg.position.set(side*.19,.83,0);let thigh=mesh(new THREE.CapsuleGeometry(.13,.58,6,10),pants);thigh.position.y=-.25;leg.add(thigh);let foot=mesh(new THREE.BoxGeometry(.24,.13,.42),shoe);foot.position.set(0,-.61,.09);leg.add(foot);hero.add(leg);parts['leg'+side]=leg;let arm=new THREE.Group();arm.position.set(side*.46,1.72,0);let a=mesh(new THREE.CapsuleGeometry(.11,.48,6,10),shirt);a.position.y=-.27;arm.add(a);hero.add(arm);parts['arm'+side]=arm}
}
function animatePose(kind,t){let w=Math.sin(t*10);if(kind==='walk'){parts['leg1'].rotation.x=w*.65;parts['leg-1'].rotation.x=-w*.65;parts['arm1'].rotation.x=-w*.45;parts['arm-1'].rotation.x=w*.45;parts.torso.rotation.z=Math.sin(t*5)*.025}else if(kind==='cook'){parts['arm1'].rotation.x=-1.1+Math.sin(t*7)*.18;parts['arm-1'].rotation.x=-1.0+Math.sin(t*7+1)*.18;parts.torso.rotation.x=.08}else if(kind==='sleep'){parts.head.rotation.z=Math.sin(t)*.02}else{parts['leg1'].rotation.x=parts['leg-1'].rotation.x=parts['arm1'].rotation.x=parts['arm-1'].rotation.x=0;parts.torso.rotation.z=Math.sin(t*2)*.01}}
function blocked(x,z){let r=.38;if(x<-10.4||x>10.4||z<-6.4||z>12)return true;return solids.some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)}
function move(dx,dz){let nx=hero.position.x+dx,nz=hero.position.z+dz;if(!blocked(nx,hero.position.z))hero.position.x=nx;if(!blocked(hero.position.x,nz))hero.position.z=nz}
function nearest(){return items.map(o=>({...o,d:Math.hypot(o.x-hero.position.x,o.z-hero.position.z)})).filter(o=>o.d<3).sort((a,b)=>a.d-b.d)}
function hudRender(){let n=nearest();hud.innerHTML=`<div class="sim-top"><div class="profile"><div class="portrait">${S.gender==='male'?'♂':'♀'}</div><div><strong>${S.name}</strong><small>День ${S.day} · ${String(Math.floor(S.time/60)%24).padStart(2,'0')}:${String(Math.floor(S.time%60)).padStart(2,'0')} · ${S.action||'Свободен'}</small></div></div><div class="needs-card"><div class="needs-title">ПОТРЕБНОСТИ</div>${[['🍽️','Голод','hunger'],['⚡','Энергия','energy'],['🚿','Гигиена','hygiene'],['🎮','Досуг','fun'],['💬','Общение','social']].map(a=>`<div class="need"><span>${a[0]} ${a[1]}</span><b>${Math.round(S[a[2]])}</b><i><em style="width:${S[a[2]]}%"></em></i></div>`).join('')}</div><div class="top-actions"><button id="pause">${paused?'▶':'Ⅱ'}</button><button id="save">💾</button></div></div><div class="bottom-hud"><div class="sim-stats"><strong>§ ${Math.round(S.money)}</strong><span>Настроение ${Math.round(S.mood)}</span><span>🍳 ${S.cooking.toFixed(1)} · 🧠 ${S.logic.toFixed(1)}</span></div><div class="context-actions">${n.map(o=>`<button class="context" data-name="${o.name}"><b>${o.icon}</b><span>${o.label}</span><small>${o.name}</small></button>`).join('')}</div></div>`;$('pause').onclick=e=>{e.stopPropagation();paused=!paused};$('save').onclick=e=>{e.stopPropagation();save()};hud.querySelectorAll('.context').forEach(b=>b.onclick=e=>{e.stopPropagation();act(b.dataset.name)})}
function act(name){if(busy||mini)return;let o=items.find(x=>x.name===name);if(!o)return;if(Math.hypot(o.x-hero.position.x,o.z-hero.position.z)>1.35){target={x:o.x,z:o.z+(o.z>1?-.9:.9),action:o.type};S.action='Идёт к '+name;return}target=null;if(o.type==='sleep')simple('Спит',5,()=>{S.energy=Math.min(100,S.energy+55);S.mood=Math.min(100,S.mood+8)});else if(o.type==='shower')simple('Принимает душ',3,()=>S.hygiene=Math.min(100,S.hygiene+42));else if(o.type==='tv')simple('Смотрит телевизор',3,()=>S.fun=Math.min(100,S.fun+30));else if(o.type==='social')simple('Общается',3,()=>S.social=Math.min(100,S.social+35));else miniGame(o.type)}
function simple(label,sec,done){busy=true;S.action=label;let started=performance.now();function finish(){done();S.action='Свободен';busy=false}setTimeout(finish,sec*1000)}
function miniGame(type){mini={type,round:0,score:0,order:[],input:[],phase:'show'};let e=document.createElement('div');e.id='mini';e.className='mini-overlay';e.innerHTML=`<div class="mini-card"><div class="mini-round">${type==='cook'?'🍳 КУХНЯ':'💼 РАБОТА'} · ЭТАП <b id="mr">1</b>/3</div><h2 id="mt">${type==='cook'?'Приготовим блюдо':'Рабочее задание'}</h2><p id="mp">Сначала запомни последовательность, затем повтори её. Каждый этап становится сложнее.</p><div id="challenge"></div><button id="miniStart">Начать</button></div>`;game.appendChild(e);$('miniStart').onclick=()=>nextRound()}
function nextRound(){mini.round++;mini.phase='input';mini.input=[];let symbols=mini.type==='cook'?['🥕','🍅','🧂','🥚','🔪','🍞']:['1','2','3','4','5','6'];mini.order=Array.from({length:mini.round+2},()=>symbols[Math.floor(Math.random()*symbols.length)]);let c=$('#challenge');c.innerHTML=`<div class="sequence">${mini.order.map(x=>`<span>${x}</span>`).join('')}</div><div class="work-keys">${symbols.slice(0,mini.type==='cook'?6:4).map(x=>`<button data-v="${x}">${x}</button>`).join('')}</div>`;$('#miniStart').textContent='Повторить';$('#miniStart').style.display='none';setTimeout(()=>{$('.sequence').classList.add('hide')},900+mini.round*250);c.querySelectorAll('button').forEach(b=>b.onclick=()=>miniInput(b.dataset.v))}
function miniInput(v){let need=mini.order[mini.input.length];if(v!==need){mini.score=Math.max(0,mini.score);toast('Ошибка — попробуй лучше');finishMini(false);return}mini.input.push(v);if(mini.input.length===mini.order.length){mini.score++;if(mini.round<3){$('#mr').textContent=mini.round+1;setTimeout(nextRound,450)}else finishMini(true)}}
function finishMini(){let good=mini.score;let rank=good===3?'ОТЛИЧНО':good===2?'ХОРОШО':'ПЛОХО';document.querySelector('.mini-overlay')?.remove();if(mini.type==='cook'){let gain=good===3?36:good===2?22:8;S.hunger=Math.min(100,S.hunger+gain);S.cooking+=good===3?1.2:.35;S.mood=Math.max(0,Math.min(100,S.mood+(good===3?12:good===2?5:-5)));S.action='Приготовил: '+rank}else{S.money+=good===3?100:good===2?55:15;S.logic+=good===3?.9:.25;S.action='Работа: '+rank}toast(rank);mini=null;busy=true;setTimeout(()=>{S.action='Свободен';busy=false},1300)}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0xa9c8d7);scene.fog=new THREE.Fog(0xa9c8d7,40,100);camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,160);camera.position.set(12,11,16);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;view.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xeef8ff,0x4d6148,2.3));let sun=new THREE.DirectionalLight(0xfff0d2,3.1);sun.position.set(-18,26,14);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);makeWorld();human();makeJoy();renderer.domElement.addEventListener('pointerdown',tap);addEventListener('resize',resize);hudRender();requestAnimationFrame(loop)}
function makeJoy(){let j=document.createElement('div');j.id='joystick';j.innerHTML='<div class="joy-ring"><div class="joy-knob"></div></div>';game.append(j);let r=j.firstElementChild,k=r.firstElementChild,on=false;function set(e){let b=r.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,l=Math.hypot(dx,dy),m=40;if(l>m){dx*=m/l;dy*=m/l}joy.x=dx/m;joy.y=dy/m;k.style.transform=`translate(${dx}px,${dy}px)`}r.onpointerdown=e=>{e.stopPropagation();on=true;r.setPointerCapture(e.pointerId);set(e)};r.onpointermove=e=>{if(on){e.stopPropagation();set(e)}};r.onpointerup=r.onpointercancel=()=>{on=false;joy.x=joy.y=0;k.style.transform=''}}
function tap(e){if(mini||busy||e.target!==renderer.domElement)return;let b=renderer.domElement.getBoundingClientRect();ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);let p=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0)),p))target={x:THREE.MathUtils.clamp(p.x,-9.5,9.5),z:THREE.MathUtils.clamp(p.z,-5.5,11.5)}}
function loop(t){requestAnimationFrame(loop);let dt=Math.min(.05,(t-last)/1000);last=t;if(!paused&&!mini){S.time+=dt*1.8;if(S.time>=1440){S.time-=1440;S.day++}S.hunger=Math.max(0,S.hunger-dt*.18);S.energy=Math.max(0,S.energy-dt*.11);S.hygiene=Math.max(0,S.hygiene-dt*.07);S.fun=Math.max(0,S.fun-dt*.06);S.social=Math.max(0,S.social-dt*.04);let dx=(keys.d?1:0)-(keys.a?1:0)+joy.x,dz=(keys.s?1:0)-(keys.w?1:0)+joy.y,m=Math.hypot(dx,dz);if(m>.08){dx/=Math.max(1,m);dz/=Math.max(1,m);move(dx*dt*4.1,dz*dt*4.1);hero.rotation.y=Math.atan2(dx,dz);animatePose('walk',t/1000);target=null}else if(target){let tx=target.x-hero.position.x,tz=target.z-hero.position.z,l=Math.hypot(tx,tz);if(l>.12){move(tx/l*dt*3.5,tz/l*dt*3.5);hero.rotation.y=Math.atan2(tx,tz);animatePose('walk',t/1000)}else{let a=target.action;target=null;if(a)setTimeout(()=>act(items.find(x=>x.type===a)?.name),150)}}else animatePose(busy&&S.action?.includes('Готов')?'cook':busy&&S.action?.includes('Спит')?'sleep':'idle',t/1000);camGoal.set(hero.position.x+11,9.5,hero.position.z+13);camera.position.lerp(camGoal,.06);camera.lookAt(hero.position.x,1.15,hero.position.z);if(Math.floor(t/250)!==Math.floor((t-dt*1000)/250))hudRender()}renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function bind(){show(menu);$('playBtn').onclick=()=>{show(game);if(!renderer)init()};$('continueBtn').onclick=()=>{show(game);if(!renderer)init()};$('newBtn').onclick=()=>show(creator);$('backBtn').onclick=()=>show(menu);$('startBtn').onclick=()=>{S.name=$('nameInput').value.trim()||'Владимир';show(game);if(!renderer)init()};document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gender]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.gender=b.dataset.gender});document.querySelectorAll('.skin').forEach(b=>b.onclick=()=>{document.querySelectorAll('.skin').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.skin=b.dataset.skin});document.querySelectorAll('.hair').forEach(b=>b.onclick=()=>{document.querySelectorAll('.hair').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.hair=b.dataset.hair})}bind();