import * as THREE from 'https://esm.sh/three@0.180.0';
import {GLTFLoader} from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js?deps=three@0.180.0';
const $=id=>document.getElementById(id), menu=$('menu'),creator=$('creator'),game=$('game'),view=$('viewport'),hud=$('hud');
const KEY='minisims-v40';
let S={name:'Владимир',gender:'male',skin:'#d59b72',hair:'#39271f',money:1850,time:510,day:1,hunger:82,energy:76,hygiene:82,fun:70,social:64,cooking:1,logic:1,mood:75,x:0,z:3};try{Object.assign(S,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
let scene,camera,renderer,hero,model,mixer,anims={},clock=new THREE.Clock(),ray,target=null,joy={x:0,y:0},keys={},solids=[],items=[],npcs=[],busy=false,paused=false,mini=null,actionTimer=0,walkPhase=0;
const mats={wall:new THREE.MeshStandardMaterial({color:0xe9e0d4,roughness:.9}),wood:new THREE.MeshStandardMaterial({color:0x80583d,roughness:.8}),grass:new THREE.MeshStandardMaterial({color:0x668f62,roughness:1}),road:new THREE.MeshStandardMaterial({color:0x70777b,roughness:1})};
function show(e){[menu,creator,game].forEach(x=>x.classList.add('hidden'));e.classList.remove('hidden')}
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function save(){localStorage.setItem(KEY,JSON.stringify(S));toast('Игра сохранена')}
function mat(c,r=.75){return new THREE.MeshStandardMaterial({color:c,roughness:r})}
function box(name,x,y,z,w,h,d,c,solid=true){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.name=name;m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);if(solid)solids.push({x,z,w,d});return m}
function cylinder(x,y,z,r,h,c){let m=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.9,h,12),mat(c));m.position.set(x,y,z);m.castShadow=true;scene.add(m);return m}
function makeWorld(){
 let g=new THREE.Mesh(new THREE.PlaneGeometry(90,90),mats.grass);g.rotation.x=-Math.PI/2;g.receiveShadow=true;scene.add(g);
 box('road',0,.02,17,70,.04,8,0x70777b,false);box('road2',-24,.025,17,8,.045,70,0x70777b,false);box('sidewalk',0,.04,12,70,.06,2,0xb9b4a9,false);
 // house shell with open front
 box('back wall',0,2,-6,20,4,.28,0xe9e0d4);box('left wall',-10,2,2,.28,4,16,0xe9e0d4);box('right wall',10,2,2,.28,4,16,0xe9e0d4);box('frontL',-7,2,10,6,4,.28,0xe9e0d4);box('frontR',7,2,10,6,4,.28,0xe9e0d4);
 box('floor',0,.02,2,20,.1,16,0xc9b99f,false);box('rug',-3,.08,4,6,.04,4,0xa77f70,false);
 box('kitchen',5,.65,-3.9,7,1.3,1.3,0x566b7e);box('counter',5,.65,-2.4,7,1.3,.9,0x75614f);box('fridge',8,1.35,-4.9,1.1,2.7,1.1,0xe9ecee);box('bed',-5,.65,-3.7,3.7,1.1,4.2,0x536e9c);box('blanket',-5,1.24,-3.5,3.3,.08,3.2,0x7894bb,false);box('sofa',-5,.7,4.3,4.5,1.3,1.5,0x806a61);box('tvstand',0,.55,5.7,3.6,.9,.9,0x624936);box('tv',0,1.65,5.25,3.2,1.8,.18,0x11171c);box('desk',5,.65,4.2,3,1.2,1.2,0x765238);box('monitor',5,1.55,3.95,1.8,1.3,.12,0x17252d);box('shower',7.8,1.1,-.5,2,2.2,2,0x9cc5ca);box('toilet',5.5,.6,-.1,1,1.1,1.3,0xf2eee7);
 // garden fence, lamps and decorative trees
 for(let x=-9;x<=9;x+=3){box('fence',x,1,11.5,.16,2,.16,0x8b6b4d)}
 for(const x of[-17,-11,14,20]){cylinder(x,1.6,13,.12,3,0x30353a);let l=new THREE.PointLight(0xffdca8,1.4,8);l.position.set(x,3.1,13);scene.add(l);}
 for(let i=0;i<34;i++){let x=-38+Math.random()*76,z=-28+Math.random()*58;if(Math.abs(x)<13&&z<13)continue;tree(x,z)}
 items=[
  {name:'Кухня',icon:'🍳',x:5,z:-3.1,type:'cook',label:'Приготовить блюдо'},
  {name:'Кровать',icon:'🛏️',x:-5,z:-2.0,type:'sleep',label:'Спать'},
  {name:'Телевизор',icon:'📺',x:0,z:4.0,type:'tv',label:'Смотреть'},
  {name:'Душ',icon:'🚿',x:7.8,z:1.1,type:'shower',label:'Принять душ'},
  {name:'Компьютер',icon:'💻',x:5,z:3.0,type:'work',label:'Работать'},
  {name:'Диван',icon:'💬',x:-5,z:3.2,type:'social',label:'Общаться'}];
}
function tree(x,z){cylinder(x,.9,z,.25,1.8,0x60432f);let c=new THREE.Mesh(new THREE.IcosahedronGeometry(1.7,1),mat(0x47764b));c.position.set(x,2.5,z);c.castShadow=true;scene.add(c)}
function makeNPC(x,z,color,name){let n=new THREE.Group();n.position.set(x,0,z);let body=new THREE.Mesh(new THREE.CapsuleGeometry(.4,.85,5,10),mat(color));body.position.y=1.1;n.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.37,16,12),mat(0xc98f68));head.position.y=2;n.add(head);let hair=new THREE.Mesh(new THREE.SphereGeometry(.39,16,8,0,Math.PI*2,0,Math.PI*.45),mat(0x38271e));hair.position.y=2.14;n.add(hair);scene.add(n);npcs.push({g:n,name,x,z,phase:Math.random()*10,target:null})}
function makeHero(){hero=new THREE.Group();hero.position.set(S.x,0,S.z);scene.add(hero);let loader=new GLTFLoader();loader.load('https://threejs.org/examples/models/gltf/Soldier.glb',g=>{model=g.scene;model.scale.setScalar(1.05);model.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});hero.add(model);mixer=new THREE.AnimationMixer(model);for(const a of g.animations)anims[a.name]=mixer.clipAction(a);play('Idle')},undefined,()=>makeStylizedHero())}
function makeStylizedHero(){let body=new THREE.Mesh(new THREE.CapsuleGeometry(.43,.95,7,14),mat(0x3d79b4));body.position.y=1.15;hero.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.4,20,14),mat(S.skin));head.position.y=2.15;hero.add(head);let hair=new THREE.Mesh(new THREE.SphereGeometry(.42,20,10,0,Math.PI*2,0,Math.PI*.48),mat(S.hair));hair.position.y=2.3;hero.add(hair);}
function play(n){if(!mixer)return;let map={Idle:'Idle',Walk:'Walk',Run:'Run',Cook:'TPose',Sit:'Idle',Talk:'Walk'};let a=anims[map[n]]||anims.Idle;if(!a)return;Object.values(anims).forEach(v=>v!==a&&v.fadeOut(.15));a.reset().fadeIn(.15).play()}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0xa9c9d8);scene.fog=new THREE.Fog(0xa9c9d8,38,100);camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,180);camera.position.set(12,11,15);try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;view.replaceChildren(renderer.domElement)}catch(e){view.innerHTML='<div style="color:white;padding:40px;font:700 18px system-ui">3D-графика не поддерживается браузером.</div>';return}
 scene.add(new THREE.HemisphereLight(0xeaf7ff,0x4c6148,2.4));let sun=new THREE.DirectionalLight(0xfff0d0,3.2);sun.position.set(-20,28,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);makeWorld();makeHero();makeNPC(-2,7,0x8b668b,'Анна');makeNPC(13,15,0x6b7f9d,'Макс');makeNPC(-16,18,0xb17b5c,'Лена');makeJoystick();ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',tap);addEventListener('resize',resize);setInterval(hudRender,250);requestAnimationFrame(loop)}
function makeJoystick(){let j=document.createElement('div');j.id='joystick';j.innerHTML='<div class="joy-ring"><div class="joy-knob"></div></div>';game.appendChild(j);let r=j.firstElementChild,k=r.firstElementChild,on=false;function set(e){let b=r.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,l=Math.hypot(dx,dy),m=40;if(l>m){dx=dx/l*m;dy=dy/l*m}joy.x=dx/m;joy.y=dy/m;k.style.transform=`translate(${dx}px,${dy}px)`}r.onpointerdown=e=>{e.stopPropagation();on=true;r.setPointerCapture(e.pointerId);set(e)};r.onpointermove=e=>{if(on){e.stopPropagation();set(e)}};r.onpointerup=r.onpointercancel=e=>{on=false;joy.x=joy.y=0;k.style.transform=''}}
function tap(e){if(mini||busy||e.target!==renderer.domElement)return;let b=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);let p=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p)){target={x:THREE.MathUtils.clamp(p.x,-8.3,8.3),z:THREE.MathUtils.clamp(p.z,-5.2,12.7)}}}
function blocked(x,z){let r=.45;return x<-8.8||x>8.8||z<-5.2||z>12.8||solids.some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)}
function move(dx,dz){let nx=hero.position.x+dx,nz=hero.position.z+dz;if(!blocked(nx,hero.position.z))hero.position.x=nx;if(!blocked(hero.position.x,nz))hero.position.z=nz}
function nearItems(){return items.map(o=>({...o,d:Math.hypot(o.x-hero.position.x,o.z-hero.position.z)})).filter(o=>o.d<3.1).sort((a,b)=>a.d-b.d)}
function hudRender(){if(!hero)return;let near=nearItems();hud.innerHTML=`<div class="sim-top"><div class="profile"><div class="portrait">${S.gender==='male'?'♂':'♀'}</div><div><strong>${S.name}</strong><small>День ${S.day} · ${String(Math.floor(S.time/60)%24).padStart(2,'0')}:${String(Math.floor(S.time%60)).padStart(2,'0')} · ${S.action||'Свободен'}</small></div></div><div class="needs-card"><div class="needs-title">ПОТРЕБНОСТИ</div>${[['🍽️','Голод','hunger'],['⚡','Энергия','energy'],['🚿','Гигиена','hygiene'],['🎮','Досуг','fun'],['💬','Общение','social']].map(a=>`<div class="need"><span>${a[0]} ${a[1]}</span><b>${Math.round(S[a[2]])}</b><i><em style="width:${Math.max(0,S[a[2]])}%"></em></i></div>`).join('')}</div><div class="top-actions"><button id="pause">${paused?'▶':'Ⅱ'}</button><button id="save">💾</button></div></div><div class="bottom-hud"><div class="sim-stats"><strong>§ ${Math.round(S.money)}</strong><span>Настроение ${Math.round(S.mood)}</span><span>🍳 ${S.cooking.toFixed(1)} · 🧠 ${S.logic.toFixed(1)}</span></div><div class="context-actions">${near.map(o=>`<button class="context" data-o="${o.name}"><b>${o.icon}</b><span>${o.name}</span><small>${o.label}</small></button>`).join('')}</div></div>`;$('save').onclick=e=>{e.stopPropagation();save()};$('pause').onclick=e=>{e.stopPropagation();paused=!paused};hud.querySelectorAll('[data-o]').forEach(b=>b.onclick=e=>{e.stopPropagation();act(b.dataset.o)})}
function act(name){if(busy||mini)return;let o=items.find(x=>x.name===name);if(!o)return;let d=Math.hypot(o.x-hero.position.x,o.z-hero.position.z);if(d>1.65){target={x:o.x,z:o.z+(o.z>1?-.95:.95),action:o.name};S.action='Идёт к '+name;return}target=null;if(o.type==='sleep')simpleAction('Спит',5000,()=>{S.energy=Math.min(100,S.energy+48);S.action='Проснулся';play('Idle')});else if(o.type==='shower')simpleAction('Принимает душ',3200,()=>S.hygiene=Math.min(100,S.hygiene+42));else if(o.type==='tv')simpleAction('Смотрит телевизор',2800,()=>S.fun=Math.min(100,S.fun+30));else if(o.type==='social')simpleAction('Общается',3000,()=>S.social=Math.min(100,S.social+34));else startMini(o.type)}
function simpleAction(label,ms,done){busy=true;S.action=label;actionTimer=ms/1000;play(label==='Спит'||label.includes('телевизор')?'Sit':'Talk');let t=setTimeout(()=>{done();S.action='Свободен';busy=false},ms)}
function startMini(type){mini={type,round:1,score:0,p:.2,d:.9,phase:type==='cook'?0:0};let e=document.createElement('div');e.id='mini';e.className='mini-overlay';e.innerHTML=type==='cook'?`<div class="mini-card"><div class="mini-round">КУХНЯ · ЭТАП 1/3</div><h2>Приготовь блюдо</h2><p>Сначала нарежь ингредиенты. Нажимай, когда маркер внутри узкой зоны.</p><div class="skill-track"><div class="skill-zone" style="left:42%;width:16%"></div><div class="skill-cursor" id="cursor"></div></div><button id="hit">🔪 НАРЕЗАТЬ</button><div class="mini-round" id="info">Ошибки портят блюдо</div></div>`:`<div class="mini-card"><div class="mini-round">РАБОТА · ЭТАП 1/3</div><h2>Рабочий день</h2><p>Следи за сигналом и нажимай кнопку в правильный момент.</p><div class="skill-track"><div class="skill-zone"></div><div class="skill-cursor" id="cursor"></div></div><button id="hit">ВЫПОЛНИТЬ</button><div class="mini-round" id="info">Точность: 0</div></div>`;game.appendChild(e);e.querySelector('#hit').onclick=hitMini}
function hitMini(){let dist=Math.abs(mini.p-.5),points=dist<.07?3:dist<.17?2:dist<.29?1:0;mini.score+=points;if(mini.round<3){mini.round++;mini.d+=.55;mini.p=.1+Math.random()*.8;let card=$('#mini .mini-card');card.querySelector('.mini-round').textContent=`${mini.type==='cook'?'КУХНЯ':'РАБОТА'} · ЭТАП ${mini.round}/3`;if(mini.type==='cook'){let names=['Нарежь ингредиенты','Поймай температуру','Собери подачу'];card.querySelector('h2').textContent=names[mini.round-1];card.querySelector('#hit').textContent=['🔪 НАРЕЗАТЬ','🔥 СНЯТЬ С ОГНЯ','🍽️ ПОДАТЬ'][mini.round-1]}card.querySelector('#info').textContent=`Точность: ${mini.score} · промахов: ${3-mini.round}`;return}let result=mini.score>=8?'ОТЛИЧНО':mini.score>=5?'ХОРОШО':'ПЛОХО';$('#mini').remove();mini=null;busy=true;S.action=result;play('Cook');if(type==='cook'){S.hunger=Math.min(100,S.hunger+(result==='ОТЛИЧНО'?38:result==='ХОРОШО'?24:8));S.cooking+=result==='ОТЛИЧНО'?.45:result==='ХОРОШО'?.22:.05}else{S.money+=result==='ОТЛИЧНО'?160:result==='ХОРОШО'?90:25;S.logic+=result==='ОТЛИЧНО'?.35:result==='ХОРОШО'?.15:.04}save();setTimeout(()=>{busy=false;S.action='Свободен'},1400);toast(type==='cook'?`Блюдо: ${result}`:`Работа: ${result}`)}
function tick(dt){if(paused||!hero)return;S.time+=dt*.8;if(S.time>=1440){S.time=0;S.day++}if(!busy&&!mini){S.hunger-=dt*.018;S.energy-=dt*.009;S.hygiene-=dt*.012;S.fun-=dt*.01;S.social-=dt*.007}S.mood=Math.max(0,Math.min(100,(S.hunger+S.energy+S.hygiene+S.fun+S.social)/5));if(mini){mini.p+=mini.d*dt;if(mini.p>.96||mini.p<.04)mini.d*=-1;let c=$('cursor');if(c)c.style.left=`calc(${mini.p*100}% - 3px)`;return}
 let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0)+joy.x,dz=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0)+joy.y;if(target&&!busy){dx+=target.x-hero.position.x;dz+=target.z-hero.position.z;let l=Math.hypot(dx,dz);if(l<.35){let o=items.find(q=>q.name===target.action);target=null;if(o)act(o.name)}else{dx/=l;dz/=l}}if((dx||dz)&&!busy){let l=Math.hypot(dx,dz);move(dx/l*dt*3.2,dz/l*dt*3.2);hero.rotation.y=Math.atan2(dx,dz);walkPhase+=dt*10;play('Walk')}else if(!busy)play('Idle');if(mixer)mixer.update(dt);for(const n of npcs){n.phase+=dt*.4;n.g.position.x=n.x+Math.sin(n.phase)*1.5;n.g.position.z=n.z+Math.cos(n.phase*.7)*1.1}camera.position.lerp(new THREE.Vector3(hero.position.x+11,10,hero.position.z+13),.055);camera.lookAt(hero.position.x,1,hero.position.z)}
function loop(t){requestAnimationFrame(loop);let dt=Math.min(.05,clock.getDelta());tick(dt);if(renderer)renderer.render(scene,camera)}
function resize(){if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
$('#newBtn').onclick=()=>show(creator);$('#backBtn').onclick=()=>show(menu);$('#playBtn').onclick=()=>{show(game);if(!scene)init()};$('#continueBtn').onclick=()=>{show(game);if(!scene)init()};$('#startBtn').onclick=()=>{S.name=$('#nameInput').value.trim()||'Владимир';save();show(game);if(!scene)init()};document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gender]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.gender=b.dataset.gender});document.querySelectorAll('.skin').forEach(b=>b.onclick=()=>{document.querySelectorAll('.skin').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.skin=b.dataset.skin;$('#pHead').style.background=S.skin});document.querySelectorAll('.hair').forEach(b=>b.onclick=()=>{document.querySelectorAll('.hair').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.hair=b.dataset.hair;$('#pHair').style.background=S.hair});
show(menu);