import * as THREE from 'https://esm.sh/three@0.180.0';
import { OrbitControls } from 'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js?deps=three@0.180.0';

const $=id=>document.getElementById(id);
const menu=$('menu'),creator=$('creator'),game=$('game'),viewport=$('viewport'),hud=$('hud'),toast=$('toast');
const KEY='minisims-v8';
const defaults={name:'Сим',gender:'male',skin:'#d59b72',hair:'#39271f',shirt:'#4c78b8',money:1850,time:480,hunger:78,energy:82,hygiene:76,fun:70,social:62,mood:78,cooking:1,logic:1,charisma:1,jobXp:0,jobLevel:1,day:1,x:0,z:4,speed:1,action:'Свободен'};
let state={...defaults};try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
let scene,camera,renderer,controls,sim,clock=new THREE.Clock(),raycaster,target=null,keys={},joy={x:0,y:0},worldObjects=[],mini=null,running=false,ui=0,walkTime=0,daySky=0;
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.58,metalness:.03});
function add(o){o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function mesh(g,c,p=[0,0,0],r=[0,0,0],parent=scene){const o=new THREE.Mesh(g,M(c));o.position.set(...p);o.rotation.set(...r);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function box(w,h,d,c,x,y,z,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),c,[x,y,z],undefined,parent)}
function cyl(r,h,c,x,y,z,parent=scene){return mesh(new THREE.CylinderGeometry(r,r*.92,h,24),c,[x,y,z],undefined,parent)}
function sphere(r,c,x,y,z,parent=scene){return mesh(new THREE.SphereGeometry(r,24,16),c,[x,y,z],undefined,parent)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function note(t){toast.textContent=t;toast.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function show(el){[menu,creator,game].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}
function setupCreator(){document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{state.gender=b.dataset.gender;document.querySelectorAll('[data-gender]').forEach(x=>x.classList.toggle('active',x===b));updatePreview()});document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{state.skin=b.dataset.skin;document.querySelectorAll('[data-skin]').forEach(x=>x.classList.toggle('active',x===b));updatePreview()});document.querySelectorAll('[data-hair]').forEach(b=>b.onclick=()=>{state.hair=b.dataset.hair;document.querySelectorAll('[data-hair]').forEach(x=>x.classList.toggle('active',x===b));updatePreview()});$('backBtn').onclick=()=>show(menu);$('startBtn').onclick=()=>{state.name=$('nameInput').value.trim()||'Сим';save();startGame()};$('playBtn').onclick=startGame;$('newBtn').onclick=()=>show(creator);$('continueBtn').onclick=startGame;updatePreview()}
function updatePreview(){$('pHead').style.background=state.skin;$('pHair').style.background=state.hair;$('pShirt').style.background=state.gender==='male'?'#4c78b8':'#a85478'}
function ground(){const g=mesh(new THREE.PlaneGeometry(100,100), '#7da06d',[0,0,20],[ -Math.PI/2,0,0]);g.receiveShadow=true;for(let x=-40;x<=40;x+=5){box(4,.035,2.2,x,.025,15,'#8eaa77')}box(100,.04,5,'#6f7676',0,.04,17);box(5,.05,100,'#777d7d',0,.045,20);for(let z=-20;z<70;z+=6)box(1,.06,4,'#d2bd82',0,.07,z);for(let x=-45;x<50;x+=10){tree(x,7+(x%3)*2);tree(x+4,34-(x%5))}}
function tree(x,z){cyl(.24,2.6,'#684936',x,1.3,z);const crown=sphere(1.45,'#4f8153',x,3.0,z);sphere(1.05,'#63945d',x-.8,3.1,z+.2);sphere(.9,'#568654',x+.75,3.0,z-.35)}
function room(){box(18,.25,13,'#c8b59e',0,.12,0);box(18,3.7,.22,'#eee7dd',0,2,-6.5);box(.22,3.7,13,'#eee7dd',-9,2,0);box(.22,3.7,13,'#eee7dd',9,2,0);box(.18,3.6,7.2,'#e9dfd4',0,1.8,-2.8);box(18,.2,.2,'#e9dfd4',0,3.6,-6.5);box(8.8,.08,6,'#cbb69c',-4.5,.28,-3.3);box(8.8,.08,6,'#b5a88e',4.5,.28,-3.3);box(8.8,.08,6,'#c0b99f',-4.5,.28,2.8);box(8.8,.08,6,'#d0b68d',4.5,.28,2.8);windowFrame(-3.4,2.2,-6.34,3.2,1.5);windowFrame(4.8,2.2,-6.34,3.2,1.5);door();}
function windowFrame(x,y,z,w,h){box(w,h,.08,'#a9d5e5',x,y,z);box(w+.15,.13,.12,'#6b6258',x,y+h/2,z);box(w+.15,.13,.12,'#6b6258',x,y-h/2,z);box(.13,h,.12,'#6b6258',x-w/2,y,z);box(.13,h,.12,'#6b6258',x+w/2,y,z);box(.08,h,.13,'#6b6258',x,y,z);box(w,.08,.13,'#6b6258',x,y,z)}
function door(){box(1.5,3,.18,'#754e39',8.87,1.5,-1);box(1.1,2.2,.03,'#4b83a0',8.78,1.55,-.98);sphere(.06,'#d9b35d',8.72,1.5,-.88)}
function sofa(x,z){box(3.2,.55,1.05,'#536b8c',x,.62,z);box(3.05,1.05,.28,'#647fa2',x,1.15,z+.38);box(.22,.65,1.1,'#455b78',x-1.48,.78,z);box(.22,.65,1.1,'#455b78',x+1.48,.78,z)}
function bed(x,z){box(3.5,.45,2.4,'#f0eee9',x,.55,z);box(3.3,.25,1.5,'#708db6',x,.86,z-.35);box(3.35,1,.25,'#d9d0c5',x,1.05,z-1.05);box(.35,.6,2.2,'#7a5944',x-1.7,.7,z)}
function kitchen(x,z){box(5.8,.85,.7,'#e8e5df',x,.82,z);for(let i=0;i<3;i++){box(.62,.04,.5,'#2b3135',x-1.9+i*1.25,1.27,z);cyl(.16,.06,'#c9d0d2',x-1.9+i*1.25,1.31,z)}box(.8,1.8,.65,'#dce4e7',x-2.5,1.35,z);box(.8,1.8,.65,'#f3f1eb',x+2.5,1.35,z);}
function tv(x,z){box(2.4,1.5,.16,'#1b2229',x,1.7,z);box(2.05,1.15,.04,'#29465a',x,1.72,z-.1);box(.18,1,.45,'#443a32',x,1.0,z);box(1.8,.1,.7,'#624a37',x,.65,z)}
function shower(x,z){box(1.7,2,.08,'#a7d3dc',x,1.25,z);box(1.7,.1,.08,'#6c9ba6',x,2.25,z);cyl(.45,.12,'#d7e6e8',x,1.1,z);}
function computer(x,z){box(1.8,.12,1,'#76583f',x,.85,z);box(.95,1,.08,'#1f2830',x,1.38,z-.28);box(.8,.55,.03,'#4b88aa',x,1.38,z-.33);box(.15,.65,.15,'#383d42',x,1.2,z+.15)}
function buildWorld(){ground();room();bed(-5.5,-3.8);kitchen(5.6,4.2);sofa(-5.7,3.9);tv(-5.7,5.7);shower(5,-1.8);box(.9,1.1,.75,'#f4f1eb',7.1,.95,-3.7);box(1.2,.1,1.2,'#8bbbc6',5,-1.8);computer(-2.7,-4.1);box(1.7,.1,1,'#805d43',5.6,1.0,2.5);cyl(.45,.08,'#e5d5bc',5.6,1.08,2.5);for(let i=0;i<6;i++)lamp(-7+i*3,5.9);worldObjects=[['Кровать','🛏️',-5.5,-3.8,'sleep'],['Холодильник','🍳',3.1,4.2,'cook'],['Телевизор','📺',-5.7,5.7,'tv'],['Душ','🚿',5,-1.8,'shower'],['Туалет','🚽',7.1,-3.7,'toilet'],['Стол','🍽️',5.6,2.5,'eat'],['Компьютер','💻',-2.7,-4.1,'computer'],['Диван','🛋️',-5.7,3.9,'social']].map(a=>({name:a[0],icon:a[1],x:a[2],z:a[3],type:a[4],pending:false}))}
function lamp(x,z){cyl(.08,.9,'#55473c',x,2.5,z);sphere(.25,'#ead8a5',x,3,z)}
function createSim(){sim=new THREE.Group();scene.add(sim);sim.position.set(state.x,0,state.z);const skin=M(state.skin),shirt=M(state.gender==='male'?'#4d78b6':'#b65a7b'),pants=M('#303746');const torso=mesh(new THREE.CapsuleGeometry(.39,.72,8,16),state.gender==='male'?'#4d78b6':'#b65a7b',[0,1.05,0],undefined,sim);const head=mesh(new THREE.SphereGeometry(.43,24,18),state.skin,[0,1.95,0],undefined,sim);head.scale.y=1.08;const hair=mesh(new THREE.SphereGeometry(.45,24,14),state.hair,[0,2.18,0],undefined,sim);hair.scale.y=.55;const eyeL=sphere(.045,'#20252a',-.15,1.98,.41,sim),eyeR=sphere(.045,'#20252a',.15,1.98,.41,sim);const neck=box(.18,.2,.18,state.skin,0,1.58,0,sim);sim.userData={torso,head,hair,legs:[],arms:[],baseY:0};for(const x of[-.2,.2]){const l=mesh(new THREE.CapsuleGeometry(.11,.62,7,10),'#303746',[x,.4,0],undefined,sim);l.userData.baseX=x;sim.userData.legs.push(l)}for(const x of[-.53,.53]){const a=mesh(new THREE.CapsuleGeometry(.1,.58,7,10],state.gender==='male'?'#4d78b6':'#b65a7b',[x,1.02,0],undefined,sim);a.userData.baseX=x;sim.userData.arms.push(a)}sphere(.55,'#000000',0,.03,0,sim).material.transparent=true;sim.children.at(-1).material.opacity=.12}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color('#a9c8d8');scene.fog=new THREE.Fog('#a9c8d8',28,75);camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,130);camera.position.set(13,12,16);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.replaceChildren(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=34;controls.maxPolarAngle=1.35;scene.add(new THREE.HemisphereLight(0xeaf6ff,0x526947,2.3));const sun=new THREE.DirectionalLight(0xffefcf,3.2);sun.position.set(-15,22,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);buildWorld();createSim();raycaster=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',worldClick);makeJoystick();clock.start()}
function worldClick(e){if(e.target.closest?.('#joystick'))return;const r=renderer.domElement.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(v,camera);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p)){target={x:THREE.MathUtils.clamp(p.x,-8,8),z:THREE.MathUtils.clamp(p.z,-5.8,13)};state.action='Идёт'}}
function makeJoystick(){const el=document.createElement('div');el.id='joystick';el.innerHTML='<div class="joy-ring"><div class="joy-knob"></div></div>';game.appendChild(el);const ring=el.firstElementChild,knob=ring.firstElementChild;let active=false;const update=e=>{const b=ring.getBoundingClientRect();let x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,d=Math.hypot(x,y),m=43;if(d>m){x=x/d*m;y=y/d*m}joy.x=x/m;joy.y=y/m;knob.style.transform=`translate(${x}px,${y}px)`};ring.onpointerdown=e=>{active=true;ring.setPointerCapture(e.pointerId);update(e)};ring.onpointermove=e=>active&&update(e);ring.onpointerup=ring.onpointercancel=()=>{active=false;joy.x=joy.y=0;knob.style.transform='translate(0,0)'}}
function move(dt){if(mini)return;let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0)+joy.x;let dz=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0)+joy.y;if(target){const tx=target.x-sim.position.x,tz=target.z-sim.position.z,d=Math.hypot(tx,tz);if(d>.2){dx+=tx/d;dz+=tz/d}else{target=null;const o=worldObjects.find(x=>x.pending);if(o){o.pending=false;startMini(o.type,o.name)}}}if(dx||dz){const l=Math.hypot(dx,dz);sim.position.x=THREE.MathUtils.clamp(sim.position.x+dx/l*dt*2.9*state.speed,-8.1,8.1);sim.position.z=THREE.MathUtils.clamp(sim.position.z+dz/l*dt*2.9*state.speed,-5.8,13.2);state.x=sim.position.x;state.z=sim.position.z;state.action='Идёт';sim.rotation.y=Math.atan2(dx,dz);walkTime+=dt*10;sim.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(walkTime+(i?Math.PI:0))*.45);sim.userData.arms.forEach((a,i)=>a.rotation.x=Math.sin(walkTime+(i?Math.PI:0))*.3);sim.position.y=Math.abs(Math.sin(walkTime))*.035}else{sim.userData.legs.forEach(l=>l.rotation.x*=.8);sim.userData.arms.forEach(a=>a.rotation.x*=.8);sim.position.y=0}}
const labels={cook:'Приготовить блюдо',eat:'Поесть',sleep:'Лечь спать',shower:'Принять душ',toilet:'Сходить в туалет',tv:'Смотреть телевизор',computer:'Работать',social:'Пообщаться'};
function go(name){const o=worldObjects.find(x=>x.name===name);if(!o)return;const d=Math.hypot(o.x-sim.position.x,o.z-sim.position.z);if(d>1.8){worldObjects.forEach(x=>x.pending=false);o.pending=true;target={x:o.x,z:o.z+(o.z>0?-1:1)};state.action='Идёт к '+name}else startMini(o.type,name)}
function needsHTML(){return `<div class="needs-card"><div class="needs-title">ПОТРЕБНОСТИ</div>${[['Голод',state.hunger,'🍽️'],['Энергия',state.energy,'⚡'],['Гигиена',state.hygiene,'🚿'],['Досуг',state.fun,'🎮'],['Общение',state.social,'💬']].map(a=>`<div class="need"><span>${a[2]} ${a[0]}</span><b>${Math.round(a[1])}</b><i><em style="width:${a[1]}%"></em></i></div>`).join('')}</div>`}
function render(){const near=worldObjects.map(o=>({...o,d:Math.hypot(o.x-sim.position.x,o.z-sim.position.z)})).filter(o=>o.d<3.4).sort((a,b)=>a.d-b.d).slice(0,3);hud.innerHTML=`<div class="sim-top"><div class="profile"><div class="portrait">${state.gender==='male'?'♂':'♀'}</div><div><strong>${state.name}</strong><small>День ${state.day} · ${clock()} · ${state.action}</small></div></div>${needsHTML()}<div class="top-actions"><button data-speed=".5">Ⅱ</button><button data-speed="1">▶</button><button data-speed="3">▶▶</button><button id="saveBtn">💾</button><button id="homeBtn">☰</button></div></div><div class="bottom-hud"><div class="sim-stats"><strong>§ ${Math.round(state.money)}</strong><span>Настроение ${Math.round(state.mood)}</span><span>Кулинария ${state.cooking.toFixed(1)}</span></div><div class="context-actions">${near.map(o=>`<button class="context" data-object="${o.name}"><b>${o.icon}</b><span>${o.name}</span><small>${labels[o.type]}</small></button>`).join('')}</div></div>`;hud.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>state.speed=+b.dataset.speed);$('saveBtn').onclick=()=>{save();note('Сохранено')};$('homeBtn').onclick=()=>{save();running=false;show(menu)};hud.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>go(b.dataset.object))}
function clock(){return `${String(Math.floor(state.time/60)%24).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`}
function startMini(type,name){if(mini)return;mini={type,name,round:0,score:0};const title=type==='cook'?'Готовка':type==='computer'?'Работа за компьютером':type==='shower'?'Душ':type==='sleep'?'Сон':type==='social'?'Общение':type==='tv'?'Телевизор':'Действие';const el=document.createElement('div');el.className='mini-overlay';el.innerHTML=`<div class="mini-card"><div class="mini-kicker">${name}</div><h2>${title}</h2><p>Останови бегунок в зелёной зоне. Три точных попадания дадут отличный результат.</p><div class="skill-track"><div class="skill-zone"></div><div class="skill-cursor"></div></div><button id="miniTap">ПОПАСТЬ</button><div class="mini-round">Раунд <b>0</b> / 3</div></div>`;game.appendChild(el);const cursor=el.querySelector('.skill-cursor'),zone=el.querySelector('.skill-zone');let pos=4,dir=1;zone.style.left=(20+Math.random()*50)+'%';const timer=setInterval(()=>{pos+=dir*2.4;if(pos>94){pos=94;dir=-1}if(pos<2){pos=2;dir=1}cursor.style.left=pos+'%'},25);el.querySelector('#miniTap').onclick=()=>{const a=cursor.getBoundingClientRect(),b=zone.getBoundingClientRect();if(a.left<b.right&&a.right>b.left)mini.score++;mini.round++;el.querySelector('.mini-round').innerHTML=`Раунд <b>${mini.round}</b> / 3`;if(mini.round>=3){clearInterval(timer);finishMini() }else zone.style.left=(18+Math.random()*55)+'%'}}
function finishMini(){const s=mini.score,t=mini.type;let result=s===3?'ОТЛИЧНО':s===2?'ХОРОШО':'ПЛОХО';if(t==='cook'){state.hunger=Math.min(100,state.hunger+10+s*9);state.cooking+=s*.1}if(t==='eat')state.hunger=Math.min(100,state.hunger+18+s*7);if(t==='shower')state.hygiene=Math.min(100,state.hygiene+18+s*9);if(t==='sleep')state.energy=Math.min(100,state.energy+22+s*14);if(t==='tv')state.fun=Math.min(100,state.fun+12+s*8);if(t==='social')state.social=Math.min(100,state.social+12+s*8);if(t==='computer'){state.logic+=s*.1;state.jobXp+=s*12;if(state.jobXp>=100){state.jobXp-=100;state.jobLevel++;state.money+=150;note('Повышение! +§150')}}state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);document.querySelector('.mini-overlay')?.remove();mini=null;state.action=result==='ОТЛИЧНО'?'Сделал отлично':result==='ХОРОШО'?'Сделал хорошо':'Сделал плохо';note(result+'!');save();setTimeout(()=>state.action='Свободен',1500)}
function tick(dt){if(!running||mini)return;state.time+=dt*state.speed*2.4;if(state.time>=1440){state.time-=1440;state.day++}state.hunger=Math.max(0,state.hunger-dt*.55*state.speed);state.energy=Math.max(0,state.energy-dt*.22*state.speed);state.hygiene=Math.max(0,state.hygiene-dt*.16*state.speed);state.fun=Math.max(0,state.fun-dt*.13*state.speed);state.social=Math.max(0,state.social-dt*.1*state.speed);state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);move(dt);daySky=(state.time-360)/720;const light=Math.max(0,Math.sin(daySky*Math.PI));scene.background.setHSL(.56,.28,.45+.1*light)}
function startGame(){show(game);if(!running){running=true;init()}else{running=true;sim.position.set(state.x,0,state.z)}render()}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('resize',()=>{if(!camera)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function loop(){requestAnimationFrame(loop);const dt=Math.min(.05,clock.getDelta());tick(dt);if(running){controls.target.lerp(new THREE.Vector3(sim.position.x,1,sim.position.z),.09);controls.update();ui+=dt;if(ui>.18){render();ui=0}renderer.render(scene,camera)}}
setupCreator();loop();
