import * as THREE from 'https://esm.sh/three@0.180.0';
import {OrbitControls} from 'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js?deps=three@0.180.0';
const $=id=>document.getElementById(id),menu=$('menu'),creator=$('creator'),game=$('game'),viewport=$('viewport'),hud=$('hud'),toast=$('toast');
const KEY='minisims-v9';let state={name:'Сим',gender:'male',skin:'#d59b72',hair:'#39271f',money:1850,time:480,hunger:78,energy:82,hygiene:76,fun:70,social:62,mood:78,cooking:1,logic:1,jobXp:0,jobLevel:1,day:1,x:0,z:4,speed:1,action:'Свободен'};try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
let scene,camera,renderer,controls,sim,clock=new THREE.Clock(),raycaster,target=null,keys={},joy={x:0,y:0},objects=[],mini=null,running=false,ui=0,walk=0;
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.6});const add=o=>{o.castShadow=o.receiveShadow=true;scene.add(o);return o};const B=(w,h,d,c,x,y,z,p=scene)=>{let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};const C=(r,h,c,x,y,z,p=scene)=>{let o=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.9,h,20),mat(c));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};const S=(r,c,x,y,z,p=scene)=>{let o=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),mat(c));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function note(t){toast.textContent=t;toast.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>toast.classList.remove('show'),1700)}function show(e){[menu,creator,game].forEach(x=>x.classList.add('hidden'));e.classList.remove('hidden')}
function creatorBind(){document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{state.gender=b.dataset.gender;document.querySelectorAll('[data-gender]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{state.skin=b.dataset.skin;document.querySelectorAll('[data-skin]').forEach(x=>x.classList.toggle('active',x===b));$('pHead').style.background=state.skin});document.querySelectorAll('[data-hair]').forEach(b=>b.onclick=()=>{state.hair=b.dataset.hair;document.querySelectorAll('[data-hair]').forEach(x=>x.classList.toggle('active',x===b));$('pHair').style.background=state.hair});$('backBtn').onclick=()=>show(menu);$('startBtn').onclick=()=>{state.name=$('nameInput').value.trim()||'Сим';save();start()};$('playBtn').onclick=start;$('newBtn').onclick=()=>show(creator);$('continueBtn').onclick=start}
function tree(x,z,s=1){C(.2*s,2.4*s,'#684936',x,1.2*s,z);S(1.35*s,'#4e7e52',x,2.9*s,z);S(.9*s,'#65945d',x-.75*s,3.15*s,z+.25*s);S(.85*s,'#5b8958',x+.7*s,3*s,z-.3*s)}
function windowBox(x,z){B(3,.03,.06,'#a6d4e5',x,2.1,z);B(3,.12,.12,'#6b6258',x,3,z);B(3,.12,.12,'#6b6258',x,1.2,z);B(.12,1.8,.12,'#6b6258',x-1.5,2.1,z);B(.12,1.8,.12,'#6b6258',x+1.5,2.1,z);B(.1,1.8,.12,'#6b6258',x,2.1,z)}
function bed(x,z){B(3.5,.45,2.3,'#eee9e0',x,.55,z);B(3.2,.24,1.45,'#718db7',x,.88,z-.35);B(3.25,1,.22,'#d8cec1',x,1.05,z-1.05);B(.3,.6,2.1,'#76543c',x-1.7,.7,z)}
function sofa(x,z){B(3.3,.55,1,'#536d91',x,.62,z);B(3.15,1,.25,'#6683a6',x,1.15,z+.37);B(.2,.7,1,'#455a77',x-1.5,.78,z);B(.2,.7,1,'#455a77',x+1.5,.78,z)}
function kitchen(x,z){B(6,.8,.7,'#e8e4dc',x,.8,z);for(let i=-2;i<=2;i++){C(.18,.05,'#30353a',x+i*1.15,1.25,z);C(.09,.06,'#c9d0d2',x+i*1.15,1.3,z)}B(.8,1.8,.65,'#dfe6e8',x-2.55,1.3,z);B(.8,1.8,.65,'#f2f0e9',x+2.55,1.3,z)}
function tv(x,z){B(2.4,1.45,.15,'#1b2228',x,1.65,z);B(2.05,1.12,.04,'#2b566d',x,1.66,z-.1);B(.16,1,.35,'#4a3b31',x,1,z);B(1.8,.1,.7,'#684c37',x,.6,z)}
function world(){let g=new THREE.Mesh(new THREE.PlaneGeometry(100,100),mat('#7ca16d'));g.rotation.x=-Math.PI/2;g.position.z=18;g.receiveShadow=true;scene.add(g);B(18,.25,13,'#c7b59e',0,.12,0);B(18,3.6,.22,'#eee6db',0,2,-6.5);B(.22,3.6,13,'#eee6db',-9,2,0);B(.22,3.6,13,'#eee6db',9,2,0);B(.18,3.5,7,'#e7ddd1',0,1.8,-2.8);B(9,.08,6,'#c6b293',-4.5,.27,-3.3);B(9,.08,6,'#b8ad92',4.5,.27,-3.3);B(9,.08,6,'#c0b89f',-4.5,.27,2.8);B(9,.08,6,'#d1b78d',4.5,.27,2.8);windowBox(-3.2,-6.35);windowBox(4.7,-6.35);B(1.5,3,.18,'#76503a',8.88,1.5,-1);B(1.1,2.2,.04,'#4c8ba7',8.78,1.55,-.9);bed(-5.5,-3.8);kitchen(5.5,4.2);sofa(-5.7,3.9);tv(-5.7,5.7);B(1.6,2,.08,'#9bcbd5',5,1.25,-1.8);C(.42,.1,'#dce9eb',5,1.1,-1.8);B(.9,1.1,.75,'#f5f1ea',7.1,.95,-3.7);B(1.5,.1,1.2,'#87b8c2',5,-1.8);B(1.8,.12,1,'#76563e',5.6,.85,2.5);C(.45,.08,'#e6d7be',5.6,1,2.5);B(1.8,.12,1,'#76563e',-2.7,.85,-4.1);B(1,1,.08,'#202a31',-2.7,1.35,-4.38);B(.82,.55,.03,'#4d8aaa',-2.7,1.35,-4.43);for(let x=-25;x<30;x+=7)tree(x,12+(x%4)*5,.8);objects=[['Кровать','🛏️',-5.5,-3.8,'sleep'],['Холодильник','🍳',3,4.2,'cook'],['Телевизор','📺',-5.7,5.7,'tv'],['Душ','🚿',5,-1.8,'shower'],['Туалет','🚽',7.1,-3.7,'toilet'],['Стол','🍽️',5.6,2.5,'eat'],['Компьютер','💻',-2.7,-4.1,'computer'],['Диван','🛋️',-5.7,3.9,'social']].map(a=>({name:a[0],icon:a[1],x:a[2],z:a[3],type:a[4],pending:false}))}
function createSim(){sim=new THREE.Group();scene.add(sim);sim.position.set(state.x,0,state.z);const shirt=state.gender==='male'?'#4d78b6':'#b85d7d';const body=B(.72,.95,.48,shirt,0,1.05,0,sim);body.geometry=new THREE.CapsuleGeometry(.39,.72,8,16);const head=S(.43,state.skin,0,1.95,0,sim);head.scale.y=1.08;const hair=S(.46,state.hair,0,2.18,0,sim);hair.scale.y=.55;S(.045,'#20252a',-.15,1.98,.4,sim);S(.045,'#20252a',.15,1.98,.4,sim);sim.userData.legs=[];sim.userData.arms=[];for(const x of[-.2,.2]){let l=B(.22,.75,.22,'#303746',x,.42,0,sim);sim.userData.legs.push(l)}for(const x of[-.52,.52]){let a=B(.2,.7,.2,shirt,x,1.02,0,sim);sim.userData.arms.push(a)}const sh=S(.55,'#000',0,.03,0,sim);sh.scale.y=.12;sh.material.transparent=true;sh.material.opacity=.18}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color('#a9c8d8');scene.fog=new THREE.Fog('#a9c8d8',30,75);camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,130);camera.position.set(13,12,16);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.replaceChildren(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=34;controls.maxPolarAngle=1.35;scene.add(new THREE.HemisphereLight(0xeaf6ff,0x526947,2.4));const sun=new THREE.DirectionalLight(0xffefcf,3.4);sun.position.set(-15,22,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);world();createSim();raycaster=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',clickWorld);makeJoy()}
function clickWorld(e){if(e.target.closest?.('#joystick'))return;const r=renderer.domElement.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(v,camera);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p)){target={x:THREE.MathUtils.clamp(p.x,-8.2,8.2),z:THREE.MathUtils.clamp(p.z,-5.8,13)};state.action='Идёт'}}
function makeJoy(){const j=document.createElement('div');j.id='joystick';j.innerHTML='<div class="joy-ring"><div class="joy-knob"></div></div>';game.appendChild(j);const r=j.firstElementChild,k=r.firstElementChild;let on=false;const mv=e=>{const b=r.getBoundingClientRect();let x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,d=Math.hypot(x,y),m=42;if(d>m){x=x/d*m;y=y/d*m}joy.x=x/m;joy.y=y/m;k.style.transform=`translate(${x}px,${y}px)`};r.onpointerdown=e=>{on=true;r.setPointerCapture(e.pointerId);mv(e)};r.onpointermove=e=>on&&mv(e);r.onpointerup=r.onpointercancel=()=>{on=false;joy.x=joy.y=0;k.style.transform='translate(0,0)'}}
function move(dt){if(mini)return;let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0)+joy.x,dz=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0)+joy.y;if(target){let tx=target.x-sim.position.x,tz=target.z-sim.position.z,d=Math.hypot(tx,tz);if(d>.18){dx+=tx/d;dz+=tz/d}else{target=null;const o=objects.find(x=>x.pending);if(o){o.pending=false;startMini(o.type,o.name)}}}if(dx||dz){let l=Math.hypot(dx,dz);sim.position.x=THREE.MathUtils.clamp(sim.position.x+dx/l*dt*2.9*state.speed,-8.2,8.2);sim.position.z=THREE.MathUtils.clamp(sim.position.z+dz/l*dt*2.9*state.speed,-5.8,13);state.x=sim.position.x;state.z=sim.position.z;state.action='Идёт';sim.rotation.y=Math.atan2(dx,dz);walk+=dt*10;sim.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(walk+(i?Math.PI:0))*.45);sim.userData.arms.forEach((a,i)=>a.rotation.x=Math.sin(walk+(i?Math.PI:0))*.3);sim.position.y=Math.abs(Math.sin(walk))*.035}else sim.position.y=0}
const labels={cook:'Приготовить блюдо',eat:'Поесть',sleep:'Лечь спать',shower:'Принять душ',toilet:'В туалет',tv:'Смотреть ТВ',computer:'Работать',social:'Общаться'};function go(name){const o=objects.find(x=>x.name===name);if(!o)return;let d=Math.hypot(o.x-sim.position.x,o.z-sim.position.z);if(d>1.8){objects.forEach(x=>x.pending=false);o.pending=true;target={x:o.x,z:o.z+(o.z>0?-1:1)};state.action='Идёт к '+name}else startMini(o.type,name)}
function needs(){return `<div class="needs-card"><div class="needs-title">ПОТРЕБНОСТИ</div>${[['Голод',state.hunger,'🍽️'],['Энергия',state.energy,'⚡'],['Гигиена',state.hygiene,'🚿'],['Досуг',state.fun,'🎮'],['Общение',state.social,'💬']].map(a=>`<div class="need"><span>${a[2]} ${a[0]}</span><b>${Math.round(a[1])}</b><i><em style="width:${a[1]}%"></em></i></div>`).join('')}</div>`}
function render(){const near=objects.map(o=>({...o,d:Math.hypot(o.x-sim.position.x,o.z-sim.position.z)})).filter(o=>o.d<3.5).sort((a,b)=>a.d-b.d).slice(0,3);hud.innerHTML=`<div class="sim-top"><div class="profile"><div class="portrait">${state.gender==='male'?'♂':'♀'}</div><div><strong>${state.name}</strong><small>День ${state.day} · ${clockText()} · ${state.action}</small></div></div>${needs()}<div class="top-actions"><button data-speed=".5">Ⅱ</button><button data-speed="1">▶</button><button data-speed="3">▶▶</button><button id="saveBtn">💾</button><button id="homeBtn">☰</button></div></div><div class="bottom-hud"><div class="sim-stats"><strong>§ ${Math.round(state.money)}</strong><span>Настроение ${Math.round(state.mood)}</span><span>Кулинария ${state.cooking.toFixed(1)}</span></div><div class="context-actions">${near.map(o=>`<button class="context" data-object="${o.name}"><b>${o.icon}</b><span>${o.name}</span><small>${labels[o.type]}</small></button>`).join('')}</div></div>`;hud.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>state.speed=+b.dataset.speed);$('saveBtn').onclick=()=>{save();note('Сохранено')};$('homeBtn').onclick=()=>{save();running=false;show(menu)};hud.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>go(b.dataset.object))}
function clockText(){return `${String(Math.floor(state.time/60)%24).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`}
function startMini(type,name){if(mini)return;mini={type,name,round:0,score:0};const title=type==='cook'?'🍳 Готовка':type==='computer'?'💻 Работа':type==='shower'?'🚿 Душ':type==='sleep'?'🛏️ Сон':type==='social'?'💬 Общение':type==='tv'?'📺 Телевизор':'🎯 Действие';const el=document.createElement('div');el.className='mini-overlay';el.innerHTML=`<div class="mini-card"><div class="mini-kicker">${name}</div><h2>${title}</h2><p>Останови бегунок внутри зелёной зоны. Три раунда: результат влияет на качество действия.</p><div class="skill-track"><div class="skill-zone"></div><div class="skill-cursor"></div></div><button id="miniTap">ПОПАСТЬ</button><div class="mini-round">Раунд <b>0</b> / 3</div></div>`;game.appendChild(el);const c=el.querySelector('.skill-cursor'),z=el.querySelector('.skill-zone');let p=3,d=1;z.style.left=(18+Math.random()*55)+'%';const timer=setInterval(()=>{p+=d*2.5;if(p>94){p=94;d=-1}if(p<2){p=2;d=1}c.style.left=p+'%'},25);el.querySelector('#miniTap').onclick=()=>{const a=c.getBoundingClientRect(),b=z.getBoundingClientRect();if(a.left<b.right&&a.right>b.left)mini.score++;mini.round++;el.querySelector('.mini-round').innerHTML=`Раунд <b>${mini.round}</b> / 3`;if(mini.round>=3){clearInterval(timer);finishMini()}else z.style.left=(18+Math.random()*55)+'%'}}
function finishMini(){const s=mini.score,t=mini.type;const result=s===3?'ОТЛИЧНО':s===2?'ХОРОШО':'ПЛОХО';if(t==='cook'){state.hunger=Math.min(100,state.hunger+12+s*9);state.cooking+=s*.1}if(t==='eat')state.hunger=Math.min(100,state.hunger+18+s*7);if(t==='shower')state.hygiene=Math.min(100,state.hygiene+18+s*9);if(t==='sleep')state.energy=Math.min(100,state.energy+22+s*14);if(t==='tv')state.fun=Math.min(100,state.fun+12+s*8);if(t==='social')state.social=Math.min(100,state.social+12+s*8);if(t==='computer'){state.logic+=s*.1;state.jobXp+=s*12;if(state.jobXp>=100){state.jobXp-=100;state.jobLevel++;state.money+=150;note('Повышение! +§150')}}state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);document.querySelector('.mini-overlay')?.remove();mini=null;state.action=result==='ОТЛИЧНО'?'Сделал отлично':result==='ХОРОШО'?'Сделал хорошо':'Сделал плохо';note(result+'!');save();setTimeout(()=>state.action='Свободен',1300)}
function tick(dt){if(!running||mini)return;state.time+=dt*state.speed*2.4;if(state.time>=1440){state.time-=1440;state.day++}state.hunger=Math.max(0,state.hunger-dt*.55*state.speed);state.energy=Math.max(0,state.energy-dt*.22*state.speed);state.hygiene=Math.max(0,state.hygiene-dt*.16*state.speed);state.fun=Math.max(0,state.fun-dt*.13*state.speed);state.social=Math.max(0,state.social-dt*.1*state.speed);state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);move(dt)}
function start(){show(game);if(!running){running=true;init()}else{running=true;sim.position.set(state.x,0,state.z)}render()}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('resize',()=>{if(camera){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}});function loop(){requestAnimationFrame(loop);const dt=Math.min(.05,clock.getDelta());tick(dt);if(running){controls.target.lerp(new THREE.Vector3(sim.position.x,1,sim.position.z),.09);controls.update();ui+=dt;if(ui>.18){render();ui=0}renderer.render(scene,camera)}}creatorBind();loop();
