import * as THREE from 'https://esm.sh/three@0.180.0';
import { OrbitControls } from 'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js?deps=three@0.180.0';

const $=id=>document.getElementById(id);
const menu=$('menu'), creator=$('creator'), game=$('game'), viewport=$('viewport'), hud=$('hud'), toast=$('toast');
const state={time:480,money:1850,speed:1,hunger:62,energy:82,hygiene:76,fun:68,social:55,mood:74,action:'Свободен',name:'Сим',gender:'male',skin:'#d59b72',hair:'#39271f'};
try{Object.assign(state,JSON.parse(localStorage.getItem('minisims-save-v2')||'{}'));}catch(e){}
function show(el){[menu,creator,game].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden');}
function saveGame(){localStorage.setItem('minisims-save-v2',JSON.stringify(state));}
function notify(t){if(!toast)return;toast.textContent=t;toast.classList.add('show');clearTimeout(window.__miniToast);window.__miniToast=setTimeout(()=>toast.classList.remove('show'),1400);}
function startGame(){state.name=state.name||'Сим';saveGame();show(game);if(!started){started=true;try{init3D();}catch(e){console.error(e);notify('Ошибка 3D: '+e.message)}}renderUI();}
function openCreator(){show(creator);}
function backMenu(){show(menu);}
$('playBtn').addEventListener('click',startGame);$('playBtn').addEventListener('touchend',e=>{e.preventDefault();startGame()},{passive:false});
$('newBtn').addEventListener('click',openCreator);$('newBtn').addEventListener('touchend',e=>{e.preventDefault();openCreator()},{passive:false});
$('continueBtn').addEventListener('click',startGame);$('continueBtn').addEventListener('touchend',e=>{e.preventDefault();startGame()},{passive:false});
$('backBtn').addEventListener('click',backMenu);$('backBtn').addEventListener('touchend',e=>{e.preventDefault();backMenu()},{passive:false});
$('startBtn').addEventListener('click',()=>{state.name=$('nameInput').value.trim()||'Сим';saveGame();startGame()});$('startBtn').addEventListener('touchend',e=>{e.preventDefault();state.name=$('nameInput').value.trim()||'Сим';saveGame();startGame()},{passive:false});
let gender=state.gender||'male';
document.querySelectorAll('[data-gender]').forEach(b=>b.addEventListener('click',()=>{gender=b.dataset.gender;state.gender=gender;document.querySelectorAll('[data-gender]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('pShirt').style.background=gender==='male'?'#5b78a8':'#a85b79'}));
document.querySelectorAll('.skin').forEach(b=>b.addEventListener('click',()=>{state.skin=b.dataset.skin;$('pHead').style.background=state.skin;document.querySelectorAll('.skin').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
document.querySelectorAll('.hair').forEach(b=>b.addEventListener('click',()=>{state.hair=b.dataset.hair;$('pHair').style.background=state.hair;document.querySelectorAll('.hair').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
let started=false,scene=null,camera=null,renderer=null,controls=null,sim=null;
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.7})}
function box(w,h,d,c,x,y,z,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function init3D(){scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc5dd);scene.fog=new THREE.Fog(0x9fc5dd,30,80);camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,120);camera.position.set(16,13,18);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.innerHTML='';viewport.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=38;controls.maxPolarAngle=1.35;controls.target.set(0,1,0);scene.add(new THREE.HemisphereLight(0xffffff,0x557052,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-10,18,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
box(16,.2,13,0x9b9992,0,0,0);box(16,3.4,.2,0xd8d0c3,0,1.7,-6.5);box(.2,3.4,13,0xd8d0c3,-8,1.7,0);box(.2,3.4,13,0xd8d0c3,8,1.7,0);box(16,3.4,.2,0xd8d0c3,0,1.7,6.5);
box(3.4,.65,2.3,0x557ba8,-4,.33,-3.5);box(1.2,2.5,1.1,0xe9edf2,-4,1.25,1.8);box(2.4,.9,1.1,0x796450,-2.1,.45,1.8);box(2.4,1.4,.45,0x171b20,2.8,1.8,-4.9);box(3.8,.9,1.2,0x996673,3,-.05,-3.1);box(1.5,2.3,1.5,0x86b9c7,5.2,1.15,1.8);box(1.1,1.1,1.1,0xf0f0ec,3.2,.55,2);box(1.5,1,.9,0x343a44,-1,.5,-4);box(2.3,.8,1.1,0x8a6a4c,-1,.4,-2);
box(40,.1,30,0x6f9a69,0,-.25,17);for(let i=0;i<12;i++){const x=-17+(i%6)*6.5,z=8+Math.floor(i/6)*8;box(.3,2.2,.3,0x71553b,x,1,z);const c=new THREE.Mesh(new THREE.IcosahedronGeometry(1.25,1),mat(0x4e7e50));c.position.set(x,2.8,z);c.castShadow=true;scene.add(c)}
sim=new THREE.Group();scene.add(sim);box(.85,1.35,.5,state.gender==='male'?0x4d6fa8:0xa84d72,0,.95,0,sim);box(.64,.64,.64,state.skin,0,1.95,0,sim);box(.28,.9,.28,0x30343b,-.2,.25,0,sim);box(.28,.9,.28,0x30343b,.2,.25,0,sim);box(.22,1,.22,state.skin,-.58,1,0,sim);box(.22,1,.22,state.skin,.58,1,0,sim);box(.78,.2,.72,state.hair,0,2.27,0,sim);
}
function bar(label,v){return `<div class="need"><div class="label"><span>${label}</span><span>${Math.round(v)}</span></div><div class="bar"><div class="fill" style="width:${Math.max(0,Math.min(100,v))}%;background:${v<20?'#ff6b78':v<45?'#ffc857':'#55d98a'}"></div></div></div>`}
function clock(){return `${String(Math.floor(state.time/60)%24).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`}
function renderUI(){if(!hud)return;hud.innerHTML=`<div class="topbar"><div class="panel sim-card"><div class="avatar">${state.gender==='male'?'♂':'♀'}</div><div><div class="name">${state.name}</div><div class="sub">${state.action} · ${clock()}</div></div></div><div class="panel needs">${bar('🍽️ Голод',state.hunger)}${bar('⚡ Энергия',state.energy)}${bar('🚿 Гигиена',state.hygiene)}${bar('🎮 Досуг',state.fun)}${bar('💬 Общение',state.social)}</div><div class="panel controls"><button class="icon-btn speed" data-speed="0.5">▶</button><button class="icon-btn speed" data-speed="1">▶▶</button><button class="icon-btn speed" data-speed="3">▶▶▶</button><button class="icon-btn" id="saveBtn">💾</button><button class="icon-btn" id="menuBtn">☰</button></div></div><div class="bottom"><div class="panel actionbar"><button class="action" data-action="cook"><div class="ico">🍳</div><span>Готовить</span></button><button class="action" data-action="sleep"><div class="ico">🛏️</div><span>Спать</span></button><button class="action" data-action="shower"><div class="ico">🚿</div><span>Душ</span></button><button class="action" data-action="fun"><div class="ico">📺</div><span>ТВ</span></button><button class="action" data-action="social"><div class="ico">💬</div><span>Общаться</span></button><button class="action" data-action="work"><div class="ico">💼</div><span>Работать</span></button></div><div class="panel side"><div class="money">§ ${Math.round(state.money)}</div><div class="stat"><span>Настроение</span><b>${Math.round(state.mood)}</b></div><div class="stat"><span>День</span><b>${Math.floor(state.time/1440)+1}</b></div></div></div>`;hud.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed});hud.querySelector('#saveBtn').onclick=()=>{saveGame();notify('Игра сохранена')};hud.querySelector('#menuBtn').onclick=()=>{saveGame();show(menu)};hud.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.action));}
function doAction(a){const map={cook:['Готовит', 'hunger',20],sleep:['Спит','energy',25],shower:['Принимает душ','hygiene',22],fun:['Смотрит ТВ','fun',20],social:['Общается','social',20],work:['Работает',null,0]};const x=map[a];if(!x)return;state.action=x[0];if(a==='work'){state.money+=55;state.energy=Math.max(0,state.energy-10)}else state[x[1]]=Math.min(100,state[x[1]]+x[2]);state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);renderUI();}
let last=performance.now(),ui=0;function loop(now){requestAnimationFrame(loop);if(!renderer)return;const dt=Math.min(.05,(now-last)/1000);last=now;state.time=(state.time+dt*state.speed*2)%1440;state.hunger=Math.max(0,state.hunger-dt*state.speed*.025);state.energy=Math.max(0,state.energy-dt*state.speed*.018);state.hygiene=Math.max(0,state.hygiene-dt*state.speed*.012);state.fun=Math.max(0,state.fun-dt*state.speed*.01);state.social=Math.max(0,state.social-dt*state.speed*.008);state.mood=Math.round((state.hunger+state.energy+state.hygiene+state.fun+state.social)/5);ui+=dt;if(ui>.5){renderUI();ui=0}if(sim)sim.rotation.y+=dt*.12;controls.update();renderer.render(scene,camera)}requestAnimationFrame(loop);addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
show(menu);